version: "3.3"

services:
  med-postgres:
    image: postgres
    container_name: med-postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
    networks:
      - med-network

  med-postgres-test:
    image: postgres
    container_name: med-postgres-test
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT_TEST}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASS_TEST}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    volumes:
      - pgdata:/data/postgres/test
    networks:
      - med-network

  med-api:
    build: .
    container_name: med-api
    environment:
      - POSTGRES_HOST=med-postgres
    restart: always
    ports:
      - 3003:3003
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - med-network
    depends_on:
      - med-postgres

networks:
  med-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
