version: "3.3"

services:
  pebmed-postgres:
    image: postgres
    container_name: pebmed-postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
    networks:
      - pebmed-network

  pebmed-api:
    build: .
    container_name: pebmed-api
    environment:
      - POSTGRES_HOST=pebmed-postgres
    restart: always
    ports:
      - 3003:3003
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - pebmed-network
    depends_on:
      - pebmed-postgres

networks:
  pebmed-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
